### ISSUE TITLE
Settings window immediately applies changes to widget

### ISSUE THREAD

**Issue by billkendrick** [Zren/plasma-applet-dailyforecast#7]
Daily Forecast's settings window has "Ok" / "Apply" / "Cancel" buttons at the bottom. However, changes appear to be immediate (which is surprising, since most things in KDE don't work like this).

Therefore, the "Apply" button is always greyed out, and the "Cancel" button doesn't actually cancel changes (it simply acts like the "OK" button).

I'd recommend that the behavior be changed to match other KDE apps, and only apply the changes to the widget if the "Apply" or "OK" buttons are clicked.

**Comment by billkendrick** [comment]
(This is with version 5, downloaded via Plasma's "Add Widgets..."->"Get New Widgets..." option, by the way.)

**Comment by Zren** [comment]
This is deliberate. Gnome has this behavior, and I was disappointed KDE didn't follow the same pattern. Even Windows began using this pattern in their new System Settings.

I won't be using KDE's "Apply" that doesn't revert changes if you click "Cancel" instead of "Ok". It's code is more annoying as well as you have to define `cfg_propertyName` at [the top of the file](https://github.com/Zren/plasma-applet-eventcalendar/blob/cc02ef1fdb28ae589bc17a5e92edb38827d7c429/package/contents/ui/config/ConfigGeneral.qml#L16-L26).
